### ISSUE TITLE
Error compiling script.

### ISSUE THREAD

**Issue by dave-irvine** [Katharsas/ghidra-struct-importer#2]
Followed the instructions, but getting this error in the console:

```
C:\Users\dave\Desktop\ghidra_10.2.2_PUBLIC\plugins\ghidra-struct-importer-main hasn't changed, with 3 files failing in previous build(s):
ParseStructDialog.java:55: error: cannot find symbol
    private final BufferedDataTypeManager tempDtm;
                  ^
  symbol:   class BufferedDataTypeManager
  location: class structimporter.ParseStructDialog
ParseStructDialog.java:79: error: cannot find symbol
        tempDtm =  new BufferedDataTypeManager("ImportCStructDialog", programDtm);
                       ^
  symbol:   class BufferedDataTypeManager
  location: class structimporter.ParseStructDialog
ImportCStruct.java:8: error: cannot find symbol
import structimporter.ParseStructDialog;
                     ^
  symbol:   class ParseStructDialog
  location: package structimporter
ImportCStruct.java:13: error: cannot find symbol
		var dialog = new ParseStructDialog(this);
		                 ^
  symbol:   class ParseStructDialog
  location: class ImportCStruct
BufferedDataTypeManager.java:129: error: getDataOrganization() in structimporter.BufferedDataTypeManager cannot override getDataOrganization() in ghidra.program.model.data.StandAloneDataTypeManager
	public DataOrganization getDataOrganization() {
	                        ^
  overridden method is final
Note: BufferedDataTypeManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

> Unable to load script: ImportCStruct.java
>   detail: The class could not be found or loaded, perhaps due to a previous initialization error: structimporter/ParseStructDialog
```

This is with Ghidra 10.2.2

**Comment by Katharsas** [comment]
Did you select the `ghidra-struct-importer-main` folder when adding a scripting directory? That is the folder that contains the README.md. Works fine for me.

I will upgrade my Ghidra version and check it it works with 10.2 as well.

**Comment by dave-irvine** [comment]
Hmm yeah, looks like this in the Bundle Manager. Have just deleted, redownloaded, and changed the path to double check everything.

![image](https://user-images.githubusercontent.com/1782643/213305532-1487ff9e-37a3-45c8-84ee-39b1f126110c.png)

**Comment by Katharsas** [comment]
Yes, i just tried in Ghidra 10.2 and i get the same problem. Ghidra 10.2 is currently not compatible with my script (10.0 works). I will have to fix a bunch of stuff.

**Comment by Katharsas** [comment]
I am probably stuck until https://github.com/NationalSecurityAgency/ghidra/issues/4903 gets fixed, not sure if i can find a workaround.

**Comment by dave-irvine** [comment]
Ok no worries, if its a version requirement no problem, just wanted to be sure I wasn't doing something stupid :)

**Comment by Katharsas** [comment]
I managed to find a workaround for the issue linked above, but there are other issues as well (parser no longer returns last parsed DataType) : (

**Comment by Katharsas** [comment]
@dave-irvine
I made changes to the script and it should work now with Ghidra 10.2.2, and also has more functionality now (parsing multiple structs that depend on each other at once is now possible). However it might stop working with future versions (10.3.x) unless the linked bug gets fixed by Ghidra developers.

**Comment by call-eax** [comment]
When running the script I'm getting

```C:\Users\User\Documents\GhidraScripts\ghidra-struct-importer-0.1.0 hasn't changed, with 3 files failing in previous build(s):
ImportCStruct.java:8: error: cannot find symbol
import structimporter.ParseStructDialog;
                     ^
  symbol:   class ParseStructDialog
  location: package structimporter
ImportCStruct.java:13: error: cannot find symbol
		var dialog = new ParseStructDialog(this);
		                 ^
  symbol:   class ParseStructDialog
  location: class ImportCStruct
CParserFixed.java:1208: error: cannot find symbol
    case WCHAR:
         ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:1349: error: cannot find symbol
    case WCHAR:
         ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:1350: error: cannot find symbol
      jj_consume_token(WCHAR);
                       ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:2873: error: cannot find symbol
    case WCHAR:
         ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:4182: error: cannot find symbol
      case WCHAR:
           ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:4241: error: cannot find symbol
      case WCHAR:
           ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
CParserFixed.java:5190: warning: [removal] Double(java.lang.String) in java.lang.Double has been deprecated and marked for removal
            obj = new Double(t.image);
                  ^
CParserFixed.java:5195: warning: [removal] Character(char) in java.lang.Character has been deprecated and marked for removal
              obj = new Character(t.image.charAt(0));
                    ^
CParserFixed.java:8605: error: cannot find symbol
    if (jj_scan_token(WCHAR)) return true;
                      ^
  symbol:   variable WCHAR
  location: class structimporter.CParserFixed
Note: CParserFixed.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: CParserFixed.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
ParseStructDialog.java:182: error: cannot find symbol
        var parser = new CParserFixed(programDtm);
                         ^
  symbol:   class CParserFixed
  location: class structimporter.ParseStructDialog

> Unable to load script: ImportCStruct.java
>   detail: The class could not be found or loaded, perhaps due to a previous initialization error: structimporter/ParseStructDialog```

in Ghidra 11.2.1

![Image](https://github.com/user-attachments/assets/238b0ada-1ca4-4ab2-87b5-e6dcf0ea01bf)

**Comment by Katharsas** [comment]
@call-eax You must have used the old compat release, should work in release 0.2
Oh sorry, the new release was marked as draft, so it was invisible, should be visible now.
